companies = [
	['40 Acres / A Mule Filmworks', '4319', 'companies'],
	['Columbia TriStar', '177', 'companies'],
	['Columbia Pictures', '5', 'companies'],
	['Destination Films', '769', 'companies'],
	['Dimension Films', '7405', 'companies'],
	['Disney', '6421', 'companies'],
	['DreamWorks', '7', 'companies'],
	['DreamWorks SKG', '27', 'companies'],
	['DreamWorks Animation', '521', 'companies'],
	['DreamWorks Pictures', '7293', 'companies'],
	['Focus Features', '10146', 'companies'],
	['Fox Searchlight Pictures', '43', 'companies'],
	['Hallmark Hall of Fame Productions', '9027', 'companies'],
	['Happy Madison Productions', '2608', 'companies'],
	['IFC Films', '307', 'companies'],
	['Legendary Pictures', '923', 'companies'],
	['Lions Gate Family Entertainment', '6574', 'companies'],
	['Lions Gate Entertainments', '7035', 'companies'],
	['Lucasfilm', '1', 'companies'],
	['Magnolia Pictures', '1030', 'companies'],
	['Marvel Studios', '420', 'companies'],
	['Metro-Goldwyn-Mayer (MGM)', '8411', 'companies'],
	['New Line Cinema', '12', 'companies'],
	['Original Film', '333', 'companies'],
	['Paramount Pictures', '4', 'companies'],
	['Pixar Animation', '3', 'companies'],
	['Screen Gems', '3287', 'companies'],
	['Sony Pictures Entertainment', '5752', 'companies'],	
	['Sony Pictures', '34', 'companies'],
	['Spyglass Entertainment', '158', 'companies'],
	['Summit Entertainment', '491', 'companies'],
	['Touchstone Pictures', '9195', 'companies'],
	['United Artists', '60', 'companies'],
	['Universal Studios', '13', 'companies'],
	['Universal Cartoon Studios', '4285', 'companies'],
	['Universal Animation Studios', '5556', 'companies'],
	['Warner Bros.', '6194', 'companies'],
	['Warner Bros. Animation', '2785', 'companies'],
	['Warner Bros. Entertainment', '17', 'companies'],
	['Warner Bros. Pictures', '174', 'companies'],
	['Walt Disney Productions', '3166', 'companies'],
	['Walt Disney Production', '6470', 'companies'],
	['Walt Disney Animation Studios', '6125', 'companies'],
	['The Weinstein Company', '308', 'companies'],
	['Twentieth Century Fox Film Corporation', '306', 'companies'],
	['Touchstone Pictures', '9195', 'companies'],
	['United Artists', '60', 'companies'],
	['Universal Animation Studios', '5556', 'companies'],
	['Universal Cartoon Studios', '4285', 'companies'],
	['Universal Studios', '13', 'companies']
]

