movie_languages = [
    ['Arabic', 'ar', 'movie_languages'],
    ['Bosnian', 'bs', 'movie_languages'],
    ['Bulgarian', 'bg', 'movie_languages'],
    ['Chinese', 'zh', 'movie_languages'],
    ['Croatian', 'hr', 'movie_languages'],
    ['Dutch', 'nl', 'movie_languages'],
    ['English', 'en', 'movie_languages'],
    ['Finnish', 'fi', 'movie_languages'],
    ['French', 'fr', 'movie_languages'],
    ['German', 'de', 'movie_languages'],
    ['Greek', 'el', 'movie_languages'],
    ['Hebrew', 'he', 'movie_languages'],
    ['Hindi ', 'hi', 'movie_languages'],
    ['Hungarian', 'hu', 'movie_languages'],
    ['Icelandic', 'is', 'movie_languages'],
    ['Italian', 'it', 'movie_languages'],
    ['Japanese', 'ja', 'movie_languages'],
    ['Korean', 'ko', 'movie_languages'],
    ['Macedonian', 'mk', 'movie_languages'],
    ['Norwegian', 'no', 'movie_languages'],
    ['Persian', 'fa', 'movie_languages'],
    ['Polish', 'pl', 'movie_languages'],
    ['Portuguese', 'pt', 'movie_languages'],
    ['Punjabi', 'pa', 'movie_languages'],
    ['Romanian', 'ro', 'movie_languages'],
    ['Russian', 'ru', 'movie_languages'],
    ['Serbian', 'sr', 'movie_languages'],
    ['Slovenian', 'sl', 'movie_languages'],
    ['Spanish', 'es', 'movie_languages'],
    ['Swedish', 'sv', 'movie_languages'],
    ['Turkish', 'tr', 'movie_languages'],
    ['Ukrainian', 'uk','movie_languages']
]